pipeline
{
	agent any
	
	stages
		{
 			stage('Compile State')
 				{
 				steps
 				  {
 						withMaven(maven : 'localMaven')
 						{
							
							dir("jenkinsDemo")
							{
								sh 'mvn clean compile'
							}
							
 						}
 					}
 				}
 				
 			stage('Testing State')
 				{
 				steps
 				  {
 						withMaven(maven : 'localMaven')
 						{
 							dir("jenkinsDemo")
							{
								sh 'mvn test'
							}
							
 						}
 					}
 				}
 			stage('Package State')
 				{
 				steps
 				  {
 						withMaven(maven : 'localMaven')
 						{
 							dir("jenkinsDemo")
							{
								sh 'mvn package'
							}
							
 						}
 					}
 				}
 			stage('Install State')
 				{
 				steps
 				  {
 						withMaven(maven : 'localMaven')
 						{
 							dir("jenkinsDemo")
							{
								sh 'mvn install'
							}
							
 						}
 					}
 				}		
		}

}
