pipeline
{
	agent any
	
	stages
		{
 			stage('Compile State')
 				{
 				steps
 				  {
 						withMaven(maven : 'localMaven')
 						{
							sh 'ls -al'
							sh 'cd jenkinsDemo'
							sh 'ls -al'
							sh 'pwd'
							sh 'mvn clean compile'
 						}
 					}
 				}
 				
 			stage('Testing State')
 				{
 				steps
 				  {
 						withMaven(maven : 'localMaven')
 						{
 							sh 'mvn test'
 						}
 					}
 				}
 			stage('Deployment State')
 				{
 				steps
 				  {
 						withMaven(maven : 'localMaven')
 						{
 							sh 'mvn deploy'
 						}
 					}
 				}
 			stage('Install State')
 				{
 				steps
 				  {
 						withMaven(maven : 'localMaven')
 						{
 							sh 'mvn install'
 						}
 					}
 				}		
		}

}
